### ISSUE TITLE
Create a template for flashcards.

### ISSUE THREAD

**Issue by h010dev** [team-penguin-hackathon/flash_learning#11]
We want to have a basic template for flashcards.

**Comment by Sumit112192** [comment]
https://codepen.io/sz/pen/zYxdVJO
You can use this....

**Comment by asa-holland** [comment]
Basic flashcard template has been incorporated into student home page as part of pull request https://github.com/team-penguin-hackathon/flash_learning/pull/92. Additional support for more detailed flashcard functions will be added as separate issue.
