### ISSUE TITLE
Create a wrapper/navbar+footer+sidebar to go around pages.

### ISSUE THREAD

**Issue by h010dev** [team-penguin-hackathon/flash_learning#15]
We want some general wrappers for all pages with navigation links and other important details.

**Comment by asa-holland** [comment]
General wrapper navbar/footer/sidebar has been implemented. See pull requests https://github.com/team-penguin-hackathon/flash_learning/pull/84, https://github.com/team-penguin-hackathon/flash_learning/pull/87 and https://github.com/team-penguin-hackathon/flash_learning/pull/90
