### ISSUE TITLE
Add html/css styling to the main page.

### ISSUE THREAD

**Issue by h010dev** [team-penguin-hackathon/flash_learning#35]
Navbar with either a combined login/signup button or individual buttons.
Footer with basic copyright and site info.
Main body with a description on what the site is all about.
Contact/about sections (optional).

**Comment by chhatrapalsinhzala007** [comment]
Hello @MohamedAl-Hussein I want to contribute in this can I ?

**Comment by asa-holland** [comment]
General main page formatting has been implemented as part of https://github.com/team-penguin-hackathon/flash_learning/pull/84
