### ISSUE TITLE
Add html/css styling to the student stats page.

### ISSUE THREAD

**Issue by h010dev** [team-penguin-hackathon/flash_learning#39]

**Comment by ArtemSilka** [comment]
Hey @MohamedAl-Hussein, I would like to take on this issue. Let's discuss your expectations!

**Comment by asa-holland** [comment]
MVP for stats page has been implemented as part of pull request https://github.com/team-penguin-hackathon/flash_learning/pull/87. Specific additions to stats page should be added as new issues.
